# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [4]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[2,3,4],
              [5,6,7]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[5,6,7],
              [8,9,0],
              [1,2,3]],
              
              [[1,2,3],
              [2,3,4],
              [5,6,7]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.size, a1.dtype

((3,), 3, dtype('int32'))

In [7]:
# Attributes of 2-dimensional array
a2.shape, a2.size, a2.dtype

((2, 3), 6, dtype('int32'))

In [8]:
# Attributes of 3-dimensional array
a3.shape, a3.size, a3.dtype

((2, 3, 3), 18, dtype('int32'))

In [9]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

h = pd.DataFrame(a2, index = ["y", "x"], columns = ["a", "b", "c"])
h

a  b  c
y  2  3  4
x  5  6  7

In [10]:
# Create an array of shape (10, 2) with only ones
array = np.random.randint(10, size = (10, 2))
array

array([[3, 2],
       [3, 9],
       [2, 1],
       [3, 5],
       [2, 7],
       [4, 9],
       [9, 4],
       [2, 3],
       [8, 0],
       [7, 4]])

In [11]:
# Create an array of shape (7, 2, 3) of only zeros
zero = np.zeros((7,2,3))
zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
# Create an array within a range of 0 and 100 with step 3
array2 = np.arange( 1, 100, 3)
array2

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [13]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array3 = np.random.randint(10, size = (7, 2))
array3

array([[9, 7],
       [3, 3],
       [6, 2],
       [0, 6],
       [0, 3],
       [0, 8],
       [8, 8]])

In [14]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array4 = np.random.random_sample((3, 5))
array4

array([[0.36409885, 0.85049271, 0.82723903, 0.12658912, 0.07926398],
       [0.36742773, 0.04238085, 0.89983367, 0.14637579, 0.78643941],
       [0.69536721, 0.73960834, 0.99001199, 0.9715973 , 0.33510238]])

In [15]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
array5 = np.random.randint(10, size = (4, 6))
array5

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [16]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array6 = np.random.randint(1, 10, size = (3, 7))

# Find the unique numbers in the array you just created
np.unique(array6)

array([1, 2, 3, 4, 5, 7, 9])

In [17]:
# Find the 0'th index of the latest array you created
array6[0][0]

9

In [18]:
# Get the first 2 rows of latest array you created
array6[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [19]:
# Get the first 2 values of the first 2 rows of the latest array
array6[:2, :2]

array([[9, 1],
       [5, 3]])

In [20]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ar1 = np.random.randint(10, size = (3,5))
ar2 = np.random.randint(10, size = (3,5))

In [21]:
# Add the two arrays together
ar1 + ar2

array([[15,  8, 11,  3, 10],
       [ 7, 15, 10,  5,  6],
       [ 9, 16, 12, 13,  9]])

In [22]:
# Create another array of ones of shape (5, 3)
ar3 = np.ones((5,3))

In [23]:
# Try add the array of ones and the other most recent array together
ar3.reshape(3,5) + ar2

array([[10.,  2., 10.,  4.,  8.],
       [ 7.,  9.,  8.,  5.,  2.],
       [ 5.,  8., 10.,  9.,  9.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [24]:
# Create another array of ones of shape (3, 5)
ones_array = np.ones((3,5))

In [25]:
# Subtract the new array of ones from the other most recent array
ar3 - ones_array.T

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# Multiply the ones array with the latest array
ar3 * ones_array.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
# Take the latest array to the power of 2 using '**'
ones_array**2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# Do the same thing with np.square()
np.square(ones_array)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
# Find the mean of the latest array using np.mean()
np.mean(ones_array)

1.0

In [30]:
# Find the maximum of the latest array using np.max()
np.max(ar1)

9

In [31]:
# Find the minimum of the latest array using np.min()
np.min(ones_array)

1.0

In [32]:
# Find the standard deviation of the latest array
np.std(ones_array)

0.0

In [33]:
# Find the variance of the latest array
np.var(ones_array)

0.0

In [34]:
# Reshape the latest array to (3, 5, 1)
reshaped_one = ones_array.reshape(3, 5, 1)

In [35]:
# Transpose the latest array
reshaped_one.T

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

What does the transpose do?

In [36]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand_array = np.random.randint(10 ,size = (3,2))
rand_array2 = np.random.randint(10 ,size = (3,3))

In [37]:
# Perform a dot product on the two newest arrays you created
rand_array.T.dot(rand_array2)

array([[ 14,  42,  40],
       [ 56, 112,  32]])

In [64]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

np.random.seed(2)

ra = np.random.random((4,3))
ra2 = np.random.random((4,3))
ra

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467],
       [0.26682728, 0.62113383, 0.52914209]])

In [65]:
# Perform a dot product on the two newest arrays you created
prod = np.dot(ra, ra2.T)
prod

array([[0.17337099, 0.63620593, 0.64887622, 0.0926236 ],
       [0.33540428, 0.86412133, 0.56890794, 0.24027704],
       [0.40085389, 0.83766025, 0.37396914, 0.30741046],
       [0.45250524, 1.0015033 , 0.54270317, 0.33442005]])

It doesn't work. How would you fix it?

In [66]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
ra.dot(ra2.T)

array([[0.17337099, 0.63620593, 0.64887622, 0.0926236 ],
       [0.33540428, 0.86412133, 0.56890794, 0.24027704],
       [0.40085389, 0.83766025, 0.37396914, 0.30741046],
       [0.45250524, 1.0015033 , 0.54270317, 0.33442005]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [99]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ca = np.random.randint(10, size = (3, 10))
ca

array([[5, 0, 8, 6, 5, 1, 7, 4, 3, 6],
       [1, 4, 0, 8, 5, 4, 2, 9, 7, 1],
       [9, 2, 1, 0, 7, 1, 8, 9, 0, 7]])

In [100]:
# Compare the two arrays with '>'
ca2 = np.random.randint(10, size = (3, 10))
ca2

array([[0, 5, 2, 5, 1, 3, 3, 1, 8, 6],
       [8, 1, 5, 7, 0, 9, 1, 5, 9, 2],
       [0, 0, 4, 6, 3, 1, 8, 5, 9, 5]])

What happens when you compare the arrays with `>`?

In [101]:
# Compare the two arrays with '>='
ca > ca2

array([[ True, False,  True,  True,  True, False,  True,  True, False,
        False],
       [False,  True, False,  True,  True, False,  True,  True, False,
        False],
       [ True,  True, False, False,  True, False, False,  True, False,
         True]])

In [102]:
# Find which elements of the first array are greater than 7
ca > 7

array([[False, False,  True, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False,  True, False,
        False],
       [ True, False, False, False, False, False,  True,  True, False,
        False]])

In [103]:
# Which parts of each array are equal? (try using '==')
ca == ca2

array([[False, False, False, False, False, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True,  True, False, False,
        False]])

In [104]:
# Sort one of the arrays you just created in ascending order
ca.sort()
ca

array([[0, 1, 3, 4, 5, 5, 6, 6, 7, 8],
       [0, 1, 1, 2, 4, 4, 5, 7, 8, 9],
       [0, 0, 1, 1, 2, 7, 7, 8, 9, 9]])

In [105]:
# Sort the indexes of one of the arrays you just created
ca.argsort()

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int64)

In [106]:
# Find the index with the maximum value in one of the arrays you've created
ca.argmax()

19

In [107]:
# Find the index with the minimum value in one of the arrays you've created
ca.argmin()

0

In [108]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
ca.argmax(axis = 1)

array([9, 9, 8], dtype=int64)

In [109]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
ca.argmin(axis = 0)

array([0, 2, 1, 2, 2, 1, 1, 0, 0, 0], dtype=int64)

In [118]:
# Create an array of normally distributed random numbers
ca2 = np.random.rand()
ca2

0.46374260716574744

In [140]:
# Create an array with 10 evenly spaced numbers between 1 and 100
ca3 = np.arange(1,100)[::10]
ca3

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.